version: "2"

services:
  client:
    image: orvice/http-monitor-client
    restart: always
    volumes:
      - ./log:/var/log
    environment:
      - PORT=:8081
    container_name: http-monitor-client
    ports:
      - 8081:8081
 
